name: CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Find and Replace - Using Secrets
        run: |
          cd backend/src/main/resources
          sed -i ''s/#{MONGODBURI}#/${{ secrets.MONGODB_URI }}/g'' application.yml
      - name: Bash - Show XML Contents
        run: |
          cd backend/src/main/resources
          cat application.yml